#!/bin/sh
uniset +cat=Me +cat=Mn +cat=Cf \
	-00AD \
	+1160-11FF \
	+1929-192b \
	+302e-302f \
	+200B c | \
awk '(NR==1){sub("{","static const struct interval combining[] = {"); }{sub("^","  ");print;}'
