#!/bin/sh
[ $# = 0 ] && exec $0 EastAsianWidth.txt 
cat <<EOF
# vile:tblmode
# This file was hand-crafted from these instructions in wcwidth.c:
# "WIDTH-A" is a file extracted from EastAsianWidth.txt by selecting
# only those with width "A", and omitting:
#
#	0xAD
#	all lines with "COMBINING"
#
EOF

grep -E "^[[:xdigit:].]+;A[[:space:]]" "$@" | grep -F -v COMBINING
